import fs from "node:fs";
import path from "node:path";
import { FileModel, DirectoryModel, DependencyModel } from "../core/model.js";
import { buildDirectoryMap, formatDirectoryMap } from "./directory-map.js";
import { buildFileMap, formatFileMap } from "./file-map.js";
import { detectModules, formatModuleMap } from "./module-map.js";
import { buildEntryPointMap, formatEntryPointMap } from "./entrypoint-map.js";
import { buildManifestMap, formatManifestMap } from "./manifest-map.js";
import { formatDependencyMap } from "./dependency-map.js";
import { collectDeclaredDependencies } from "../detector/manifests.js";

export interface ProjectMapData {
  projectName: string;
  projectRoot: string;
  files: FileModel[];
  directories: DirectoryModel[];
  dependencies?: DependencyModel[];
  generatedAt?: string;
}

export function generateProjectMapContent(data: ProjectMapData): string {
  const generatedAt = data.generatedAt || new Date().toISOString();
  const dirMap = buildDirectoryMap(data.directories);
  const fileGroups = buildFileMap(data.files);
  const modules = detectModules(data.files, data.directories);
  const entryPoints = buildEntryPointMap(data.files);
  const manifests = buildManifestMap(data.files, data.projectRoot);
  const dependencies = data.dependencies !== undefined
    ? data.dependencies
    : collectDeclaredDependencies(data.files, data.projectRoot);

  const sections: string[] = [
    `# Project Map: ${data.projectName}`,
    "",
    `_Generated by Brainmap on ${generatedAt}_`,
    "",
    "## Overview",
    "",
    `- **Root**: \`${data.projectRoot}\``,
    `- **Files**: ${data.files.length}`,
    `- **Directories**: ${data.directories.length}`,
    `- **Modules**: ${modules.length}`,
    `- **Entry Points**: ${entryPoints.length}`,
    `- **Manifests**: ${manifests.length}`,
    `- **Declared Dependencies**: ${dependencies.length}`,
    "",
    formatEntryPointMap(entryPoints).trim(),
    "",
    formatModuleMap(modules).trim(),
    "",
    formatManifestMap(manifests).trim(),
    "",
    formatDependencyMap(dependencies).trim(),
    "",
    formatDirectoryMap(dirMap).trim(),
    "",
    formatFileMap(fileGroups).trim(),
    "",
  ];

  return sections.join("\n");
}

export function ensureProjectMapRoutingInIndex(brainDir: string): boolean {
  const indexPath = path.join(brainDir, "index.md");
  if (!fs.existsSync(indexPath)) {
    return false;
  }
  const content = fs.readFileSync(indexPath, "utf8");
  if (content.includes("project-map.md")) {
    return false;
  }

  const link = "- **[project-map.md](project-map.md)**: Generated map of project files, directories, modules, entry points, manifests, and declared dependencies.\n";
  let updated: string;
  if (content.includes("## Root Brain Documents\n\n")) {
    updated = content.replace("## Root Brain Documents\n\n", `## Root Brain Documents\n\n${link}`);
  } else {
    updated = `${content.trim()}\n\n${link}`;
  }
  fs.writeFileSync(indexPath, updated, "utf8");
  return true;
}

export function writeProjectMap(projectRoot: string, content: string): string {
  const brainDir = path.join(projectRoot, ".brain");
  if (!fs.existsSync(brainDir)) {
    fs.mkdirSync(brainDir, { recursive: true });
  }
  const mapPath = path.join(brainDir, "project-map.md");
  fs.writeFileSync(mapPath, content, "utf8");
  ensureProjectMapRoutingInIndex(brainDir);
  return mapPath;
}

export function updateProjectMapIncrementally(
  projectRoot: string,
  model: { name?: string; files: FileModel[]; dependencies?: DependencyModel[] },
  directories: DirectoryModel[]
): { updated: boolean; path: string } {
  const mapPath = path.join(projectRoot, ".brain", "project-map.md");
  if (!fs.existsSync(mapPath)) {
    return { updated: false, path: mapPath };
  }

  const content = generateProjectMapContent({
    projectName: model.name || path.basename(projectRoot),
    projectRoot,
    files: model.files,
    directories,
    dependencies: model.dependencies,
  });

  writeProjectMap(projectRoot, content);
  return { updated: true, path: mapPath };
}
